### ISSUE TITLE
Help with using this

### ISSUE THREAD

**Issue by moranmarcel** [purdy/aws-transcribe-transcript#2]
Hi,

I am new to programming, and only know a bit of Python. This is exactly the script I need, because I have some AWS transcriptions that I want to convert to TXT files with the transcript in order (as opposed to the AWS json file). Can you add a few more instructions on how to use this? Do you recommend a specific shell or code studio? Thanks!!

M

**Comment by purdy** [comment]
What type of computer are you using? Mac or Windows? If it's a Mac, PHP should already be installed. If it's Windows, then you'll need to install PHP first.

**Comment by moranmarcel** [comment]
Ah... awesome! Thanks!

**Comment by moranmarcel** [comment]
Weird. Here's what I did so far:

1. Downloaded the transcript.php file.
2. Downloaded my AWS transcription file (put in same folder).
3. Used terminal to navigate to that folder.
4. run the php command on the AWS transcription file. 

Problem is I keep getting this: 

-bash: ./transcript.php: Permission denied 

Any tips?

**Comment by purdy** [comment]
You can't execute transcript.php directly. You have to prefix it with php:

php ./transcript.php [FILE]

If you did that and still have the permission issue, it may be because transcript.php isn't readable by you or the folder you're in isn't writable by you (it's going to try to create the transcript file in the same folder).

**Comment by aminamos** [comment]
I successfully used the script with those instructions, thank you

**Comment by purdy** [comment]
Yay, awesome! Closing this ticket.
